; =========================
; CONFIGURACIONES GENERALES
; =========================
short_open_tag = On
expose_php = Off
allow_url_fopen = On
allow_url_include = On
enable_post_data_reading = On
output_buffering = On
precision = 14
default_charset = "UTF-8"

; =========================
; MANEJO DE ERRORES
; =========================
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING
display_errors = Off
log_errors = On

; =========================
; LÍMITES DE RECURSOS
; =========================
max_execution_time = 900
max_input_time = 60
memory_limit = 3072M
max_input_vars = 10000

; =========================
; SUBIDAS DE ARCHIVOS
; =========================
file_uploads = On
upload_max_filesize = 100M
max_file_uploads = 30
post_max_size = 128M

; =========================
; SESIONES
; =========================
session.gc_maxlifetime = 21600
session.save_handler = files
session.use_cookies = 1
session.use_only_cookies = 1
session.cookie_httponly = 1

; =========================
; ZONA HORARIA
; =========================
date.timezone = "America/La_Paz"

; =========================
; SEGURIDAD - FUNCIONES DESHABILITADAS
; =========================
disable_functions = passthru,system,proc_open,popen,show_source

; =========================
; MBSTRING
; =========================
mbstring.language = all
mbstring.http_input = auto
mbstring.encoding_translation = Off
mbstring.substitute_character = none
mbstring.func_overload = 0

; =========================
; OPCACHE
; =========================
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=60
opcache.fast_shutdown=1
opcache.enable_cli=1
